### ISSUE TITLE
"Error: cannot mark object without transaction"

### ISSUE THREAD

**Issue by NickDarvey** [fsprojects/FSharp.Data.Adaptive#108]
I'm trying to build [a thing](https://github.com/NickDarvey/Fable.Yjs) with FSharp.Data.Adaptive and Fable.

When I run `npm run test+watch`, [this test case](https://github.com/NickDarvey/Fable.Yjs/blob/a869955fce5c67bef0de8bc29802ec0d23d2ad54/tests/Fable.Yjs.Adaptive.Tests/FSharp/Data/Adaptive/Codec.fs#L165-L185) fails with:

> Error: cannot mark object without transaction

<details>
<summary>Stack trace</summary>

```
FSharp.Data.Adaptive.Codec
  √ roundtrips
  √ basic updates work (834ms)
  √ Decoded.traversei (1045ms)
  1) roundtrips updates


  3 passing (3s)
  1 failing

  1) 
       FSharp.Data.Adaptive.Codec
         roundtrips updates:
     Error: cannot mark object without transaction
      at file:///~/build/tests/Fable.Yjs.Adaptive.Tests/fable_modules/FSharp.Data.Adaptive.1.2.13/Core/Transaction.fs.js:399:23
      at Operators_Lock (file:///~/build/tests/Fable.Yjs.Adaptive.Tests/fable_modules/fable-library.4.0.0-theta-018/FSharp.Core.js:65:12)
      at FSharp_Data_Adaptive_IAdaptiveObject__IAdaptiveObject_MarkOutdated (file:///~/build/tests/Fable.Yjs.Adaptive.Tests/fable_modules/FSharp.Data.Adaptive.1.2.13/Core/Transaction.fs.js:392:9)
      at ChangeableValue$1__set_Value_2B595 (file:///~/build/tests/Fable.Yjs.Adaptive.Tests/fable_modules/FSharp.Data.Adaptive.1.2.13/AdaptiveValue/AdaptiveValue.fs.js:57:9)
      at Example_AdaptiveThing__Update_2E456985 (file:///~/build/tests/Fable.Yjs.Adaptive.Tests/FSharp/Data/Adaptive/Codec.js:98:9)
      at file:///~/build/tests/Fable.Yjs.Adaptive.Tests/FSharp/Data/Adaptive/Codec.js:319:17
```

</details>

<details>
<summary>System info</summary>

- .NET 7.0.100
- FSharp.Data.Adaptive 1.2.13
- Fable 4.0.0-theta-018
</details>

I will try to get a more concise repro, but perhaps my problem is already obvious to the maintainers or this enough to guide me where to look.

**Comment by NickDarvey** [comment]
Running this code with dotnet reveals this is unlikely to be anything to do with FSharp.Data.Adaptive. It turns out I don't have an `IAdaptiveValue<>` at runtime where I'm expecting one!


<details>
<summary>Stack trace</summary>

```
System.InvalidCastException: Unable to cast object of type 'MapVal`2[System.String,System.Object]' to type 'FSharp.Data.Adaptive.IAdaptiveValue`1[System.String]'.
   at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source) in D:\a\_work\1\s\src\FSharp.Core\prim-types.fs:line 644
   at Microsoft.FSharp.Core.ResultModule.Map[T,TResult,TError](FSharpFunc`2 mapping, FSharpResult`2 result) in D:\a\_work\1\s\src\FSharp.Core\result.fs:line 12
   at FSharp.Data.Adaptive.AValModule.map@424-1.Invoke(Unit unitVar0) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 424
   at FSharp.Data.Adaptive.AValModule.ConstantVal`1.GetValue() in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 189
   at FSharp.Data.Adaptive.AValModule.ConstantVal`1.FSharp.Data.Adaptive.IAdaptiveValue<'T>.GetValue(AdaptiveToken t) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 209
   at FSharp.Data.Adaptive.AValModule.arg10@78[T](AbstractVal`1 x, AdaptiveToken token) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 80
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.GetValue(AdaptiveToken token) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 78
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.FSharp.Data.Adaptive.IAdaptiveValue<'T>.GetValue(AdaptiveToken t) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 106
   at FSharp.Data.Adaptive.AValModule.BindVal`2.Compute(AdaptiveToken token) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 306
   at FSharp.Data.Adaptive.AValModule.arg10@78[T](AbstractVal`1 x, AdaptiveToken token) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 80
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.GetValue(AdaptiveToken token) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 78
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.FSharp.Data.Adaptive.IAdaptiveValue<'T>.GetValue(AdaptiveToken t) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:lintive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 80
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.GetValue(AdaptiveToken token) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 78
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.FSharp.Data.Adaptive.IAdaptiveValue<'T>.GetValue(AdaptiveToken t) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 106
   at FSharp.Data.Adaptive.AValModule.MapVal`2.Compute(AdaptiveToken token) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 245   at FSharp.Data.Adaptive.AValModule.arg10@78[T](AbstractVal`1 x, AdaptiveToken token) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 80
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.GetValue(AdaptiveToken token) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 78
   at FSharp.Data.Adaptive.AValModule.AbstractVal`1.FSharp.Data.Adaptive.IAdaptiveValue<'T>.GetValue(AdaptiveToken t) in D:\a\FSharp.Data.Adaptive\FSharp.Data.Adaptive\src\FSharp.Data.Adaptive\AdaptiveValue\AdaptiveValue.fs:line 106   at FSI_0002.it@414-3.Invoke(Thing update) in c:\Users\nickd\source\repos\idkdelmeanytime\test.fsx:line 417
```

</details>

<details>
<summary>test.fsx</summary>

```fsharp
#r "nuget: FSharp.Data.Adaptive"
#r "nuget: Hedgehog"

open FSharp.Data.Adaptive
open Hedgehog

type Validation<'Ok, 'Error> = Result<'Ok, 'Error list>

// https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/src/FsToolkit.ErrorHandling/Validation.fs
[<RequireQualifiedAccess>]
module internal Validation =

    let inline ok (value: 'ok) : Validation<'ok, 'error> =
        Ok value

    let inline error (error: 'error) : Validation<'ok, 'error> =
        Error [ error ]

    let inline errors (errors: 'error list) : Validation<'ok, 'error> =
        Error errors

    let inline ofResult (result: Result<'ok, 'error>) : Validation<'ok, 'error> =
        Result.mapError List.singleton result

    let inline apply
        (applier: Validation<'okInput -> 'okOutput, 'error>)
        (input: Validation<'okInput, 'error>)
        : Validation<'okOutput, 'error> =
        match applier, input with
        | Ok f, Ok x ->
            Ok (f x)
        | Error errs, Ok _
        | Ok _, Error errs ->
            Error errs
        | Error errs1, Error errs2 ->
            Error (errs1 @ errs2)

    let inline map
        ([<InlineIfLambda>] mapper: 'okInput -> 'okOutput)
        (input: Validation<'okInput, 'error>)
        : Validation<'okOutput, 'error> =
        Result.map mapper input

    let inline zip
        (left: Validation<'left, 'error>)
        (right: Validation<'right, 'error>)
        : Validation<'left * 'right, 'error> =
        match left, right with
        | Ok x1res, Ok x2res ->
            Ok (x1res, x2res)
        | Error e, Ok _
        | Ok _, Error e ->
            Error e
        | Error e1, Error e2 ->
            Error (e1 @ e2)

[<RequireQualifiedAccess>]
type Kind =
    | Constant
    | Value
    | List
    | Map

[<RequireQualifiedAccess>]
type Element =
    | Constant of obj
    | Value of obj aval
    | List of Element alist
    | Map of amap<string, Element>
    with 
    member this.toKind () =
        match this with
        | Constant _ -> Kind.Constant
        | Value _ -> Kind.Value
        | List _ -> Kind.List
        | Map _ -> Kind.Map

type PathSegment = 
    | ObjectKey   of string
    | ArrayIndex  of int

type Path = PathSegment list

module Path =
    open System.Text

    let toString (path : Path) =
        let sb = StringBuilder ()
        for p in path do
            match p with
            | ObjectKey k ->
                ignore <| sb.Append $".%s{k}"
            | ArrayIndex i ->
                ignore <| sb.Append $"[%i{i}]"
        $"${sb.ToString ()}"

type Error =
    private
    | UnexpectedKind of {|
            Path : Path
            Actual : Kind
            Expected : Kind list 
        |}
    | UnexpectedType of {|
            Path : Path
            Actual : System.Type
            Expected : System.Type list 
        |}
    | MissingProperty of {| Path : Path |}

module Error =
    let print (error : Error) =
        match error with
        | UnexpectedKind e -> $"\
            {Path.toString e.Path} is of kind %A{e.Actual} but expected one of %A{e.Expected}"
        | UnexpectedType e -> $"\
            {Path.toString e.Path} is of type %A{e.Actual} but expected one of %A{e.Expected}"
        | MissingProperty e -> $"\
            {Path.toString e.Path} does not exist but was expected."

    let printAll (errors : Error list) =
        let sb = System.Text.StringBuilder ()
        ignore <| sb.Append "Failed to decode, because:"
        ignore <| sb.AppendLine ()
        for error in errors do
            ignore <| sb.Append $"- %s{print error}"
            ignore <| sb.AppendLine ()
        sb.ToString ()

type Decoded<'Result> = Validation<'Result, Error> aval
type Decoder<'Element, 'Result> = Path * 'Element -> Decoded<'Result>
type Decoder<'Result> = Decoder<Element, 'Result>

module Encode =
    let object (props : (string * Element) list) =
        let map = cmap ()
        for (key, el) in props do
            // // TODO: Unwrap avals.
            // // I'm not sure if we can represent higher order avals in Yjs so we'll need to turn a amap<_,aval<'a>> into an amap<_,'a>.
            // // Needs to recurse (in case it's an aval<aval<'a>>).
            // let el =
            //     match el with
            //     | Element.Value v ->
            //         let _ = v.AddWeakCallback(fun v -> ignore <| map.Add (key, Element.Constant v))
            //         Element.Constant v.Current
            //     | v -> v

            ignore <| map.Add (key, el) 
            
        Element.Map map
            
    let constant a =
        a |> box |> Element.Constant

    let value a =
        a |> AVal.map box |> Element.Value

    let list f a =
        a |> AList.map f |> Element.List

    let map f a =
        a |> AMap.map f |> Element.Map

module Decoded =
    let inline ofValidation (c : Validation<'a, Error>) : Decoded<'a> = AVal.constant c
    let inline ok (c : 'a) : Decoded<'a> = ofValidation <| Validation.ok c
    let inline error (e : Error) : Decoded<'a> = ofValidation <| Validation.error e
    let inline errors (e : Error list) : Decoded<'a> = ofValidation <| Validation.errors e
    let inline value (a : Decoded<'a>) = AVal.force a

    let inline map (f : 'a -> 'b) (a : Decoded<'a>) :  Decoded<'b> =
        AVal.map (Validation.map f) a

    let inline mapError f =
        AVal.map (Result.mapError f)

    let inline bind (f : 'a -> Decoded<'b>) (a : Decoded<'a>) : Decoded<'b> =
        AVal.bind (function Ok v -> f v | Error e -> errors e) a

    let traversei (f : int -> 'a -> Decoded<'b>) (source : 'a alist) : Decoded<'b alist> =

        let folder (i : int, state : Decoded<'b alist>) (next : 'a) =
            let result = adaptive {
                let! state = state
                let! next = f i next
                match state, next with
                | Ok state, Ok next ->
                    return Validation.ok <| AList.append state (AList.single next)
                | Error e, Ok _
                | Ok _, Error e ->
                    return Validation.errors e
                | Error e1, Error e2 ->
                    return Validation.errors (e1 @ e2)             
            }
            i + 1, result

        let zzz = AList.fold folder (0, AVal.constant <| Ok AList.empty) source
        let zzz = zzz |> AVal.map snd |> AVal.bind id // surely I can avoid this?
        zzz

    let flatten (decoded : Decoded<'a aval>) : Decoded<'a> = adaptive {
        match! decoded with
        | Ok value ->
            let! value = value
            return Ok value
        | Error e ->
            return Error e
    }

module Decode = 
    /// Lift a Validation<'a, Failure> to a Decoder<'a>.
    let ofValidation (result : Validation<'Result, Error>) : Decoder<_,'Result> =
        fun _ -> Decoded.ofValidation result

    /// Creates a Decoder<'a> from an 'a.
    let ok c : Decoder<_,_> =
        fun _ -> Decoded.ok c

    /// Creates a Decoder<_> from an error.
    let error e : Decoder<_,_> =
        fun _ -> Decoded.error e

    let map (f : 'a -> 'b) (a : Decoder<'a>) : Decoder<'b> =
        a >> Decoded.map f

    let bind (f : 'a -> Decoder<_,'b>) (a : Decoder<_,'a>) : Decoder<_,'b> =
        fun dep -> a dep |> Decoded.bind (fun x -> f x dep)

    let private _value (f : 'a -> Validation<'b, Error>) : Decoder<_, 'a> -> Decoder<_, 'b> =
        bind (f >> ofValidation)

    let optional f : Decoder<_> -> Decoder<_> =
        _value <| fun (path, element) ->
            match element with
            | Some el -> f (path, el) |> Validation.map Some
            | None    -> Ok None

    let required f : Decoder<_> -> Decoder<_> =
        _value <| fun (path, element) ->
            match element with
            | Some el -> f (path, el)
            | None    -> Validation.error <| MissingProperty {| Path = path |}
    
    let constant type' : Decoder<_,_> = fun (path, el) ->
        match el with
        | Element.Constant v when v.GetType () = type'->
            Decoded.ok v
        | Element.Constant v ->
            Decoded.error <| UnexpectedType {|
                Path = path
                Actual = v.GetType()
                Expected = [ type' ]
            |}
        | el ->
            Decoded.error <| UnexpectedKind {|
                Path = path
                Actual = el.toKind ()
                Expected = [ Kind.Constant ]
            |}

    [<RequiresExplicitTypeArguments>]
    let inline constant'<'a> : Decoder<'a> =
        constant (typeof<'a>)
        |> map (fun r -> r :?> 'a)

    let value type' : Decoder<_> = fun (path, el) ->
        match el with
        // // TOQUERY: it's never going to have a valid contenttype, right?
        // | Element.Value v when v.ContentType = type' ->
        //     Decoded.ok v
        // | Element.Value v ->
        //     Decoded.error <| UnexpectedType {|
        //         Path = path
        //         Actual = v.ContentType
        //         Expected = [ type' ]
        //     |}
        | Element.Value v ->
            ignore type'
            Decoded.ok v
        | el ->
            Decoded.error <| UnexpectedKind {|
                Path = path
                Actual = el.toKind ()
                Expected = [ Kind.Value ]
            |}

    [<RequiresExplicitTypeArguments>]
    let inline value'<'a> : Decoder<'a aval> =
        value (typeof<'a>)
        |> map (fun r -> r :?> 'a aval)

    let list (f : Decoder<_>) : Decoder<_> = fun (path, el) ->
        let f i el = f (ArrayIndex i :: path, el)
        match el with
        | Element.List v ->
            v |> Decoded.traversei f
        | el ->
            Decoded.error <| UnexpectedKind {|
                Path = path
                Actual = el.toKind ()
                Expected = [ Kind.List ]
            |}

    let key key (f : Decoder<_>) : Decoder<_> = fun (path, el) ->
        match el with
        | Element.Map v -> adaptive {
                let path = ObjectKey key :: path

                let! value = v |> AMap.tryFind key

                match value with
                | None -> 
                    return Validation.error <| MissingProperty {| Path = path |}
                | Some value ->
                    return! f (path, value)
            }
        | el ->
            Decoded.error <| UnexpectedKind {|
                Path = path
                Actual = el.toKind ()
                Expected = [ Kind.Map ]
            |}

    let run (decoder : Decoder<'input, 'a>) (input : 'input) : Decoded<'a> =
        decoder ([], input)

    type ObjectBuilder () =
        member _.Return x = ok x
        member _.Bind (m, f) = bind f m
        member _.ReturnFrom m = m
        member _.Zero () = ok ()
        member _.Run f = f

        member _.key (k : string, decoder : Decoder<aval<'a>>) =
            key k decoder
            >> Decoded.flatten
            // here we flatten the outer aval (changes to the mapping) with the inner aval (changes to the values)
            // does this matter?

        member _.key (k : string, decoder : Decoder<alist<'a>>) =
            key k decoder
            >> Decoded.map AList.toAVal
            >> Decoded.flatten

    let object = ObjectBuilder ()

module private Example =

    // [<ModelType>]
    type Thing =
        {
            name  : string
            value : int
        }

    // Generated by [Adaptify](https://github.com/krauthaufen/Adaptify)
    [<System.Diagnostics.CodeAnalysis.SuppressMessage("NameConventions", "*")>]
    type AdaptiveThing(value : Thing) =
        let _name_ = cval(value.name)
        let _value_ = cval(value.value)
        let mutable __value = value
        let __adaptive = AVal.custom((fun (_ : AdaptiveToken) -> __value))
        static member Create(value : Thing) = AdaptiveThing(value)
        // static member Unpersist = Adaptify.Unpersist.create (fun (value : Thing) -> AdaptiveThing(value)) (fun (adaptive : AdaptiveThing) (value : Thing) -> adaptive.Update(value))
        member __.Update(value : Thing) =
            if Microsoft.FSharp.Core.Operators.not((ShallowEqualityComparer<Thing>.ShallowEquals(value, __value))) then
                __value <- value
                __adaptive.MarkOutdated()
                _name_.Value <- value.name
                _value_.Value <- value.value
        member __.Current = __adaptive
        member __.name = _name_ :> aval<Microsoft.FSharp.Core.string>
        member __.value = _value_ :> aval<Microsoft.FSharp.Core.int>

    module Thing =
        let gen = gen {
            let! name = Gen.string (Range.linear 0 255) Gen.alphaNum
            let! value = Gen.int32 (Range.linearBounded ())
            return {
                name = name
                value = value
            }
        }


    let encode (athing : AdaptiveThing) = Encode.object [
        "name", Encode.value athing.name
        "value", Encode.value athing.value
    ]

    let decode : Decoder<Thing> = Decode.object {
        let! name = Decode.object.key ("name", Decode.value'<string>) // unit test the Decode.object.key func
        let! value = Decode.object.key ("value", Decode.value'<int>)
        return {
            name = name
            value = value
        }
    }


Property.check <| property {
    let! model = Example.Thing.gen |> Gen.map Example.AdaptiveThing
    let model' =
        model
        |> Example.encode
        |> Decode.run Example.decode
        |> Decoded.mapError Error.printAll
        |> AVal.map (function
        | Ok r -> r
        | Error e -> invalidOp e)

    let! updates = Example.Thing.gen |> Gen.list (Range.linear 0 100)

    for update in updates do
        model.Update update
    
        let value1 = AVal.force model'
        let value2 = AVal.force model.Current

        assert(value1 = value2)
}
```

</details>

**Comment by krauthaufen** [comment]
Actually MapVal implements aval<> but I think some mapping function defaulted to obj (instead of the expected string). Does the same thing happen when using net6.0?

**Comment by NickDarvey** [comment]
The [test.fsx and stack trace](https://github.com/fsprojects/FSharp.Data.Adaptive/issues/108#issuecomment-1328226939) was running with net6.0. (I've also tried 7.0.)

**Comment by krauthaufen** [comment]
I'll take a look once I have a little time, but it may be several days...

**Comment by NickDarvey** [comment]
Thank you @krauthaufen, no rush

**Comment by NickDarvey** [comment]
Using `IAdaptiveValue` instead of `obj aval` fixed things.

```diff
[<RequireQualifiedAccess>]
type Element =
    | Constant of obj
-    | Value of obj aval
+    | Value of IAdaptiveValue
    | List of Element alist
    | Map of amap<string, Element>

// ...

    let value a =
-        a |> AVal.map box |> Element.Value
+        a :> IAdaptiveValue |> Element.Value

```
